development:
  adapter: async

test:
  adapter: test

production:
  adapter: postgresql
#  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: crime_spotter_backend_production
